# Generated by CHAE KYUNG HOON
import time
import datetime
import sys
import pyautogui
import pyperclip
import smtplib
from account import *
from xpath import *
from email.message import EmailMessage
from PIL.ImageOps import grayscale
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait          #웹페이지 로딩 대기
from selenium.webdriver.support import expected_conditions as EC 
from openpyxl import load_workbook         #엑셀파일 불러오기
from openpyxl.drawing.image import Image   #엑셀 이미지 삽입
from selenium.webdriver.support.select import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import ElementClickInterceptedException

###########################################
# UI정보로 자동화
###########################################
def uiImgFind(arg):
    timeout = 90 #타임아웃 시간
    start = time.time() #시작시간
    img = None

    #이미지가 보일때까지 90초간 반복
    while img is None:
        img = pyautogui.locateOnScreen(arg, grayscale = True) #이미지 정보
        end = time.time()
        if end - start > timeout:
            print("90초 타임아웃 발생")
            sys.exit()
    pyautogui.click(img) #해당 이미지 위치로 이동하여 클릭
    pyautogui.moveTo(700,700) #다음 반복때 마우스 이미지 인식을 위해 강제이동

###########################################
# select 옵션 선택
###########################################
def selectClick(arg1):
    elems = browser.find_elements_by_tag_name("option") #화면의 option 태그를 모두 가져옴
    for elem in elems:    #반복하면서 elems 하나씩 뽑아오기
        if elem.text == ws.cell(row=2,column=y+arg1).value: #엑셀값과 일치하면 클릭
            elem.click()
            break

###########################################
# checkbox 선택
###########################################
def checkBoxClick(arg1, arg2):
    elem = browser.find_element_by_xpath(arg1)
    if "Y" == ws.cell(row=2,column=arg2).value:
        if elem.is_selected():
            print("이미 체크되어있음")
        else:
            browser.execute_script("arguments[0].click();", elem)                 #강제클릭으로 엘리먼트 에러 해결
    elif "N" == ws.cell(row=2,column=arg2).value:
        if elem.is_selected():
            browser.execute_script("arguments[0].click();", elem)                 #강제클릭으로 엘리먼트 에러 해결
        else:
            print("이미 체크되어있지 않음")

###########################################
# 메인 프로그램 시작
###########################################
wb = load_workbook("testCase_single.xlsx") #testCase1.xlsx 파일에서 wb를 불러옴
ws = wb.active  # 현재 활성화된 sheet 가져옴

options = webdriver.ChromeOptions()
options.add_experimental_option("excludeSwitches", ["enable-logging"])
browser = webdriver.Chrome(options=options)
    
hmc_url = "https://devhmc.hanwhalife.com:1080/sfa/incomeHmc?etrDvCd=01&token=aa2cb27ab1d84482aced7b5ee21c798f&sfaCmpnDvsn=01&mobUserPrno="+str(ws.cell(row=2,column=2).value)+"&mobUserDvsn=02&offcCode=00000" #HMC QA 테스트 URL
browser.get(hmc_url) #HMC QA 테스트 URL
browser.maximize_window()
browser.implicitly_wait(10)

#테스트 케이스 col건수 만큼 반복 수행
for y in range(2,ws.max_column + 1):
    if "고객명" in ws.cell(row=1,column=y).value: # 엑셀항목과 값 비교
        time.sleep(2)
        browser.implicitly_wait(10)
        time.sleep(0.5)
        custName = ws.cell(row=2,column=y).value
        if custName: #고객명이 존재할 경우
            time.sleep(0.5)
            browser.find_element(By.CSS_SELECTOR, ".search > input").send_keys(ws.cell(row=2,column=y).value) #엑셀에서 가져온 고객명 맵핑
            browser.find_element(By.CSS_SELECTOR, ".search > input").send_keys(Keys.ENTER)                    #고객명 엔터
            time.sleep(0.5)
            browser.find_element_by_xpath(hmc_xpath1).click()      #신규설계 버튼
        else: #임의설계
            time.sleep(0.5)
            browser.find_element_by_xpath(hmc_xpath0).click()      #고객없이설계(임의설계)
            time.sleep(0.5)
    elif "상품명" in ws.cell(row=1,column=y).value:
        time.sleep(2)
        browser.implicitly_wait(10)
        #상품 선택
        for i in range(1,5):            
            browser.implicitly_wait(10)
            elem = WebDriverWait(browser, 30).until(EC.presence_of_element_located((By.XPATH, hmc_xpath2_0+'/li['+str(i)+']/a'))) #엘리먼트 로딩 대기
            browser.execute_script("arguments[0].click();", elem)                 #강제클릭으로 엘리먼트 에러 해결

            browser.implicitly_wait(10)
            goodName = str(ws.cell(row=2,column=y).value) #엑셀상품코드
            
            browser.implicitly_wait(10)
            time.sleep(0.5)
            elems = browser.find_elements_by_class_name("p_name") #class_name "p_name"(상품명)을 가지는 모든 엘리먼트 가져오기
            clickYn = "N"
            for elem in elems:    #반복하면서 elems 하나씩 뽑아오기
                if elem.text:
                    if elem.text == goodName:
                        elem.click()
                        clickYn = "Y"
                        break
            if clickYn == "Y":
                break
    elif "생년월일" in ws.cell(row=1,column=y).value:
        time.sleep(0.5)
        pyautogui.moveTo(958,688) #지정한 위치로 마우스를 이동(팝업확인클릭)
        pyautogui.click()
        time.sleep(0.5)
        try:
            if ws.cell(row=2,column=y).value:
                if "계약자생년월일" in ws.cell(row=1,column=y).value:
                    browser.find_element(By.XPATH, hmc_xpath2_3).send_keys(ws.cell(row=2,column=y).value) #엑셀에서 가져온 계약자생년월일 맵핑
                elif "주피생년월일"  in ws.cell(row=1,column=y).value:
                    browser.find_element(By.XPATH, hmc_xpath2_3_4).send_keys(ws.cell(row=2,column=y).value) #엑셀에서 가져온 주피생년월일 맵핑
                elif "종피1생년월일"  in ws.cell(row=1,column=y).value:
                    browser.find_element(By.XPATH, hmc_xpath2_3_4_1).send_keys(ws.cell(row=2,column=y).value) #엑셀에서 가져온 종피1생년월일 맵핑
                elif "종피2생년월일"  in ws.cell(row=1,column=y).value:
                    browser.find_element(By.XPATH, hmc_xpath2_3_4_2).send_keys(ws.cell(row=2,column=y).value) #엑셀에서 가져온 종피2생년월일 맵핑
                elif "종피3생년월일"  in ws.cell(row=1,column=y).value:
                    browser.find_element(By.XPATH, hmc_xpath2_3_4_3).send_keys(ws.cell(row=2,column=y).value) #엑셀에서 가져온 종피3생년월일 맵핑
        except NoSuchElementException:
            pass
    elif "성별" in ws.cell(row=1,column=y).value:
        time.sleep(0.5)
        try:
            if ws.cell(row=2,column=y).value:
                if "계약자성별" in ws.cell(row=1,column=y).value:
                    if "남" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_1).click()      #엑셀에서 가져온 계약자성별(남자) 맵핑
                    else:
                        browser.find_element_by_xpath(hmc_xpath2_3_2).click()      #엑셀에서 가져온 계약자성별(여자) 맵핑
                elif "주피성별" in ws.cell(row=1,column=y).value:
                    if "남" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_5).click()      #엑셀에서 가져온 주피성별(남자) 맵핑
                    else:
                        browser.find_element_by_xpath(hmc_xpath2_3_6).click()      #엑셀에서 가져온 주피성별(여자) 맵핑
                elif "종피1성별" in ws.cell(row=1,column=y).value:
                    if "남" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_6_1).click()      #엑셀에서 가져온 종피1성별(남자) 맵핑
                    else:
                        browser.find_element(By.ID, "woman03")
                        # browser.find_element_by_xpath(hmc_xpath2_3_6_2).click()      #엑셀에서 가져온 종피1성별(여자) 맵핑
                elif "종피2성별" in ws.cell(row=1,column=y).value:
                    if "남" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_6_3).click()      #엑셀에서 가져온 종피2성별(남자) 맵핑
                    else:
                        element = browser.find_element(By.XPATH, hmc_xpath2_3_6_4)
                        browser.execute_script("arguments[0].click();", element)                 #강제클릭으로 엘리먼트 에러 해결
                elif "종피3성별" in ws.cell(row=1,column=y).value:
                    if "남" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_6_5).click()      #엑셀에서 가져온 종피3성별(남자) 맵핑
                    else:
                        browser.find_element_by_xpath(hmc_xpath2_3_6_6).click()      #엑셀에서 가져온 종피3성별(여자) 맵핑
        except NoSuchElementException:
            pass
    elif "동일" in ws.cell(row=1,column=y).value:
        time.sleep(0.5)
        try:
            if ws.cell(row=2,column=y).value:
                if "Y" in ws.cell(row=2,column=y).value:
                    browser.find_element_by_xpath(hmc_xpath2_3_3).click()      #엑셀에서 가져온 계약자와 동일 맵핑
        except NoSuchElementException:
            pass
    elif "직종" in ws.cell(row=1,column=y).value:
        time.sleep(0.5)
        try:
            if ws.cell(row=2,column=y).value:
                if "주피직종" in ws.cell(row=1,column=y).value:
                    if "비위험" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_7).click()      
                    elif "위험1" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_7_1).click()      
                    elif "위험2" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_7_2).click()      
                    elif "위험3" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_7_3).click()      
                    elif "위험4" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_7_4).click()     
                elif "종피1직종" in ws.cell(row=1,column=y).value:
                    if "비위험" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_8_1).click()      
                    elif "위험1" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_8_2).click()      
                    elif "위험2" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_8_3).click()      
                    elif "위험3" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_8_4).click()      
                    elif "위험4" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_8_5).click()     
                elif "종피2직종" in ws.cell(row=1,column=y).value:
                    if "비위험" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_9_1).click()      
                    elif "위험1" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_9_2).click()      
                    elif "위험2" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_9_3).click()      
                    elif "위험3" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_9_4).click()      
                    elif "위험4" in ws.cell(row=2,column=y).value:
                        element = browser.find_element(By.XPATH, hmc_xpath2_3_9_5)
                        browser.execute_script("arguments[0].click();", element)                 #강제클릭으로 엘리먼트 에러 해결
                elif "종피3직종" in ws.cell(row=1,column=y).value:
                    if "비위험" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_9_6).click()      
                    elif "위험1" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_9_7).click()      
                    elif "위험2" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_9_8).click()      
                    elif "위험3" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_9_9).click()      
                    elif "위험4" in ws.cell(row=2,column=y).value:
                        browser.find_element_by_xpath(hmc_xpath2_3_9_0).click()     
        except NoSuchElementException:
            pass
    elif "보험종류1" == ws.cell(row=1,column=y).value:
        time.sleep(0.5)
        try:
            element = browser.find_element(By.XPATH, hmc_xpath2_4) #보험종류변경
            browser.execute_script("arguments[0].click();", element)                 #강제클릭으로 엘리먼트 에러 해결
        except NoSuchElementException:
            print("보험종류 변경없음")
        time.sleep(0.5)

        elems1 = browser.find_elements_by_class_name("insureSelect") #class_name "insureSelect"(보험종류)을 가지는 모든 엘리먼트 가져오기
        count=0
        countDetail = []
        #보험종류 및 보험종류별 상세 갯수
        for e1 in elems1:    
            if e1.text:
                w = str(e1.text)
                countDetail.append(str(w.count('\n')))  #보험종류별 상세 갯수
                count = count+1   #보험종류 갯수
        
        for i in range(0,count): #보험종류 만큼 반복(col)
            for j in range(0,int(countDetail[i])): #보험종류별 상세 만큼 반복(row)
                elem = browser.find_element_by_xpath(hmc_xpath2_5_0+'['+str(i+1)+']/p/select/option'+'['+str(j+1)+']')
                time.sleep(0.5)
                if ws.cell(row=2+j,column=y+i).value:  #보험종류1이 존재하면 맵핑 후 다음으로 진행
                    elemText = str(ws.cell(row=2,column=y+i).value)
                    elem1 = browser.find_element_by_xpath(hmc_xpath2_5_0+'['+str(i+1)+']/p/select')
                    elem1.send_keys(elemText) #엑셀 보험종류로 select 값 셋팅

        time.sleep(0.5)
        try:
            browser.find_element_by_xpath(hmc_xpath2_6).click()      #적용 버튼    
        except NoSuchElementException:
            print("보험종류 변경 후 적용버튼이 존재하지 않아 skip")
        time.sleep(0.5)
    elif "건강" in ws.cell(row=1,column=y).value:
        time.sleep(0.5)
        browser.implicitly_wait(10)
        try:
            if custName:
                if "Y" == ws.cell(row=2,column=y).value:
                    time.sleep(0.5)
                    browser.find_element_by_xpath(hmc_xpath2_7).click()      #고객명 존재시 건강체 체크박스
            else:
                if "Y" == ws.cell(row=2,column=y).value:
                    time.sleep(0.5)
                    element = browser.find_element(By.XPATH, hmc_xpath2_7_1) #건강체 체크박스(주피)
                    browser.execute_script("arguments[0].click();", element)                 #강제클릭으로 엘리먼트 에러 해결
                    time.sleep(0.5)
                    element = browser.find_element(By.XPATH, hmc_xpath2_7_2) #건강체 체크박스(종피1)
                    browser.execute_script("arguments[0].click();", element)                 #강제클릭으로 엘리먼트 에러 해결
        except NoSuchElementException:
            pass

        time.sleep(0.5)
        browser.find_element_by_xpath(hmc_xpath3).click()        #다음 버튼    
    elif "플랜선택" in ws.cell(row=1,column=y).value:
        browser.implicitly_wait(10)
        time.sleep(3)
        if ws.cell(row=2,column=y).value:
            try:
                for i in range(1,10):
                    time.sleep(0.5)
                    if ws.cell(row=2,column=y).value == browser.find_element_by_xpath(hmc_xpath2_8+'['+str(i)+']/a/p').text:
                        browser.find_element_by_xpath(hmc_xpath2_8+'['+str(i)+']/a/p').click()      #플랜선택
                        break
            except NoSuchElementException:
                pass
        else:
            time.sleep(0.5)
            pyautogui.moveTo(940,276) # 플랜설계화면 직접설계 버튼1
            pyautogui.click()  
            time.sleep(0.5)
            pyautogui.moveTo(940,330) # 플랜설계화면 직접설계 버튼2
            pyautogui.click()  
            time.sleep(0.5)   
    elif "주계약" in ws.cell(row=1,column=y).value:
        browser.implicitly_wait(10)
        if ws.cell(row=2,column=y).value and "연금" not in ws.cell(row=2,column=4).value: #주계약 선택이 있고, 연금/저축 상품이 아니면
            if "가입" in ws.cell(row=2,column=y).value:
                browser.find_element_by_xpath(hmc_xpath5_4).click()        #가입금액
            else:
                browser.find_element_by_xpath(hmc_xpath5_5).click()        #합계보험료
            time.sleep(0.5)
            browser.find_element_by_xpath(hmc_xpath5).send_keys(ws.cell(row=2,column=y+1).value)      #가입금액 or 합계보험료
            time.sleep(0.5)
            for i in range(2,11): #연금설계탭-연금개시나이 ~ 연금선지급탭-선지급기간 9개 항목 맵핑
                if ws.cell(row=2,column=y+i).value:
                    selectClick(i)
                    time.sleep(0.5)
            for i in range(16,19): #보험기간/납입기간/납입주기 3개 항목 맵핑
                if ws.cell(row=2,column=y+i).value:    
                    selectClick(i)
                    time.sleep(0.5)
        elif "연금" in ws.cell(row=2,column=4).value or "저축" in ws.cell(row=2,column=4).value: #연금/저축
            if ws.cell(row=2,column=y+1).value: #주계약보험료가 존재하면
                browser.find_element_by_xpath(hmc_xpath5).send_keys(ws.cell(row=2,column=y+1).value)      #주계약보험료
            if ws.cell(row=2,column=y+11).value: #연금보험료(거치)가 존재하면
                browser.find_element_by_xpath(hmc_xpath5_5_1).send_keys(ws.cell(row=2,column=y+11).value)    
            if ws.cell(row=2,column=y+12).value: #연금보험료(적립)가 존재하면
                browser.find_element_by_xpath(hmc_xpath5_5_2).send_keys(ws.cell(row=2,column=y+12).value)
            
            for i in range(13,19): #연금지급형태 ~ 납입주기 6개 항목 맵핑
                if ws.cell(row=2,column=y+i).value:
                    selectClick(i)
                    time.sleep(0.5)    
        else: #플랜선택한 종신의 경우 다음단계로 스킵
            continue
        browser.implicitly_wait(10)
        if ws.cell(row=2,column=y+19).value:   #환급특약제외
            checkBoxClick(hmc_xpath5_8, y+19)
        if ws.cell(row=2,column=y+20).value:   #연금납입면제특약제외
            checkBoxClick(hmc_xpath5_8, y+20)
        element = browser.find_element(By.CSS_SELECTOR, ".b_plus:nth-child(3)")  #특약추가버튼
        browser.execute_script("arguments[0].click();", element)                 #강제클릭으로 엘리먼트 에러 해결
        time.sleep(0.5)
        
        browser.implicitly_wait(10)
        browser.find_element_by_class_name("btn_white_normal").click()        #특약전체선택1
        time.sleep(0.5)
        browser.find_element_by_class_name("btn_point_pop").click()        #특약전체추가1
        time.sleep(0.5)
    elif "특약코드" in ws.cell(row=1,column=y).value:
        browser.implicitly_wait(10)
        for x in range(2,ws.max_row + 1):
            if ws.cell(row=x,column=y).value:
                optionCode = str(ws.cell(row=x,column=y).value) #특약코드
                time.sleep(0.5)
                #특약 상세 열기
                element = browser.find_element_by_xpath('//*[@id='+optionCode+']/div/a') #특약 선택
                browser.execute_script("arguments[0].click();", element) #강제클릭으로 엘리먼트 에러 해결
                time.sleep(0.5)
                try:
                    if ws.cell(row=x,column=y+2).value: #특약금액이 존재하면
                        browser.find_element_by_xpath('//*[@id='+optionCode+']/div[2]/div/div[1]/div/input').send_keys(ws.cell(row=x,column=y+2).value) #특약금액
                    if ws.cell(row=x,column=y+3).value: #보험기간이 존재하면
                        selectClick(3)
                    if ws.cell(row=x,column=y+4).value: #납입기간이 존재하면
                        selectClick(4)
                except NoSuchElementException:
                    print("특약세트 except 처리")                        
                time.sleep(0.5)
                #특약 상세 닫기
                element = browser.find_element_by_xpath('//*[@id='+optionCode+']/div/a') #특약 선택
                browser.execute_script("arguments[0].click();", element) #강제클릭으로 엘리먼트 에러 해결
                time.sleep(0.5)            
    #마지막 col일 경우 상세결과보기 진행
    elif "비고" in ws.cell(row=1,column=y).value:
        browser.implicitly_wait(10)
        WebDriverWait(browser, 30).until(EC.presence_of_element_located((By.XPATH, hmc_xpath6)))
        browser.find_element_by_xpath(hmc_xpath6).click()       #상세결과보기
        time.sleep(5)
        browser.implicitly_wait(10)
        try:
            elem = WebDriverWait(browser, 30).until(EC.presence_of_element_located((By.XPATH, hmc_xpath7))) #계약자명으로 엘리먼트 로딩 확인
        except NoSuchElementException:
            pass
        try:
            elem = WebDriverWait(browser, 30).until(EC.presence_of_element_located((By.XPATH, hmc_xpath8))) #설계저장으로 엘리먼트 로딩 확인
            elem.click()
        except NoSuchElementException:
            pass
        browser.implicitly_wait(10)
        WebDriverWait(browser, 30).until(EC.presence_of_element_located((By.XPATH, hmc_xpath9)))
        time.sleep(1)
        browser.find_element_by_xpath(hmc_xpath9).click()       #상품설명서 미리보기
        time.sleep(15)
        pyautogui.click()
        pyautogui.hotkey("ctrl","s") #PDF 최초 저장
        # uiImgFind("OZ_IMG_DOWNLOAD_2.png")  #오즈 다운로드 이미지 파일
        time.sleep(1)
        pyautogui.moveTo(126,992) #지정한 위치로 마우스를 이동
        pyautogui.click()
        time.sleep(1)
        pyautogui.moveTo(524,59) #지정한 위치로 마우스를 이동
        pyautogui.click()
        pyautogui.hotkey("ctrl","s") #PDF 파일명 변경을 위한 저장
        # uiImgFind("file_download_2.png")  # 우측 상단 PDF 다운로드 이미지 파일
        time.sleep(1)
        pyautogui.click()
        time.sleep(1)
        pyperclip.copy("C:/Users/Administrator/Desktop/PythonWorkspace") #상품설명서 저장 경로 클립보드에 복사
        pyautogui.hotkey("ctrl","v") #붙여넣기
        time.sleep(1)
        pyautogui.press('enter') #엔터키
        time.sleep(1)

        current_datetime = datetime.datetime.now()
        dateformat = "%Y%m%d%H%M%S"
        tmp = current_datetime.strftime(dateformat) #현재시간
        filename = str(ws.cell(row=2,column=4).value)+'_'+str(ws.cell(row=2,column=3).value)+'_'+tmp

        pyautogui.moveTo(474,703) #지정한 위치로 마우스를 이동
        pyautogui.click()
        time.sleep(1)
        pyperclip.copy(filename) #상품명+고객명 클립보드에 복사
        pyautogui.hotkey("ctrl","v") #붙여넣기
        time.sleep(1)
        pyautogui.press('enter') #엔터키
        time.sleep(1)
        break
###########################################
#브라우저 종료
###########################################
browser.quit()
wb.close()

###########################################
#이메일 전송
###########################################
msg = EmailMessage()
msg["Subject"] = "[테스트 자동화]스마트 가입설계 결과" #제목
msg["From"] = EMAIL_ADDRESS #보내는 사람
#여러명에게 메일을 보낼 때
msg["To"] = "hoonnam9714@gmail.com"
# msg["To"] = "hoonnam9714@hanwha.com, kevinkim@hanwha.com"

msg.set_content(" 스마트 가입설계 테스트 자동화 결과 보내드립니다.\n 해당 메일은 테스트 자동화 프로그램에서 자동으로 발송됩니다.\n 감사합니다.") #본문

# msg.add_attachment()
with open(filename+".pdf", "rb") as f:
    msg.add_attachment(f.read(), maintype = "application", subtype= "pdf", filename = f.name) #파일을 읽어와서 타입에 맞게 설정(PDF)

with smtplib.SMTP("smtp.gmail.com",587) as smtp:
    smtp.ehlo() #연결이 잘 수립되는지 확인
    smtp.starttls() #모든 내용이 암호화되어 전송
    smtp.login(EMAIL_ADDRESS, EMAIL_PASSWORD) #로그인
    smtp.send_message(msg)
